<a href="https://colab.research.google.com/github/f4055-hayrullah/-ali-ma/blob/main/labaratuvar1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np 
import pandas as pd

In [4]:
my_array = np.array([0,1,2,3,4]) 
my_array

array([0, 1, 2, 3, 4])

In [6]:
empty_array = np.empty((3,4),dtype =int) 
empty_array

array([[61043264,        0,        0,        0],
       [       0,        0,        0,        0],
       [       0,        0,        0,        0]])

In [7]:
empty_zeros = np.zeros((3,4),dtype=int) 
empty_zeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [9]:
full_array = np.full(shape =(3,3),fill_value = 99.99,dtype=float) 
full_array

array([[99.99, 99.99, 99.99],
       [99.99, 99.99, 99.99],
       [99.99, 99.99, 99.99]])

In [10]:
my_series = pd.Series(["a","b","c","d","e"]) 
my_series

0    a
1    b
2    c
3    d
4    e
dtype: object

In [11]:
my_list =[1,2,3,4,5] 
my_list

[1, 2, 3, 4, 5]

In [12]:
arr =np.array(my_list) 
arr

array([1, 2, 3, 4, 5])

In [14]:
ser = pd.Series(my_list) 
ser

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [15]:
my_list*3

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [16]:
arr*3

array([ 3,  6,  9, 12, 15])

In [17]:
ser*3

0     3
1     6
2     9
3    12
4    15
dtype: int64

In [18]:

dail_return =pd.Series (np.random.rand(4),name="daily returs") 
dail_return

0    0.125031
1    0.342423
2    0.845596
3    0.892327
Name: daily returs, dtype: float64

In [19]:
dail_return[dail_return<0.75] #matematiksel işlemleri böyle yapar

0    0.125031
1    0.342423
Name: daily returs, dtype: float64

In [20]:
dail_return/2

0    0.062515
1    0.171211
2    0.422798
3    0.446163
Name: daily returs, dtype: float64

In [21]:
dail_return.std()

0.37782045899443484

In [22]:
dail_return.mean()

0.5513441771447234

In [ ]:
from google.colab import drive
drive.mount('/content/drive')